version: '3' # docker-compose version
services: # services which our app going to use. (list of containers we want to create)
  mongo-cont: # container name
    image: mongo # On which image container will build
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db
    networks: # adding network
      - mern-app

  app-server:
    image: app-server
    ports:
      - "5000:5000"
    depends_on:
      - mongo-cont

networks: # allow services to talk to each other while providing isolation from other docker container, running on the same host
  mern-app:
    driver: bridge

volumes: # enable persistence of database data across container restart
  mongo_db:
    driver: local

